name: Build and Deploy Function App to Staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_functions_staging:
    runs-on: ubuntu-latest
    
    env:
      DOTNET_VERSION: '9.0.x'
      AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
      AZURE_WEBAPP_SLOT: 'staging'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Clean and Publish Function App
        run: |
          rm -rf ./publish
          dotnet publish ./QuartileStore.Products.Functions/QuartileStore.Products.Functions.csproj -c Release -o ./publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function App to Staging slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          package: ./publish
          clean: true