name: Build, Test, Deploy (Staging) and Swap

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '9.0.x'
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      AZURE_WEBAPP_SLOT: staging
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --collect "XPlat Code Coverage"
  
      - name: Clean previous publish folder
        run: rm -rf ./publish

      - name: Publish Web Api
        run: dotnet publish ./QuartileStore.Api/QuartileStore.Api.csproj -c Release -o ./publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Staging slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          package: ./publish

      - name: Get staging hostname
        id: host
        run: |
          echo "HOST=$(az webapp show -g rg_quartilestore -n quartilestore --slot staging --query defaultHostName -o tsv)" >> $GITHUB_OUTPUT

      - name: Health check (staging) with retries
        run: |
          for i in {1..15}; do
            echo "Attempt $i: https://${{ steps.host.outputs.HOST }}/health"
            if curl -fsS https://${{ steps.host.outputs.HOST }}/health; then
              exit 0
            fi
            sleep 10
          done
          echo "Health check failed"; exit 1

      - name: Swap Staging -> Production
        run: |
          az webapp deployment slot swap \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --slot ${{ env.AZURE_WEBAPP_SLOT }} \
            --target-slot production