name: Build, Test, Deploy (Staging) and Swap

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '9.0.x'
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      AZURE_WEBAPP_SLOT: ${{ secrets.AZURE_WEBAPP_SLOT }}
      PACKAGE_PATH: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --collect "XPlat Code Coverage"

      - name: Publish
        run: dotnet publish ./QuartileStore.Api/QuartileStore.Api.csproj -c Release -o ${{ env.PACKAGE_PATH }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Staging slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          package: ${{ env.PACKAGE_PATH }}

      - name: Health check staging
        run: |
          curl -f https://${{ env.AZURE_WEBAPP_NAME }}-staging.azurewebsites.net/health || exit 1

      - name: Swap Staging -> Production
        run: |
          az webapp deployment slot swap \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group <SEU_RESOURCE_GROUP> \
            --slot ${{ env.AZURE_WEBAPP_SLOT }} \
            --target-slot production
